auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: 飘零DE思绪
url: http://chanboo1985.github.io
feed: /atom.xml
author_info: <a href="http://chanboo1985.github.io/">飘零DE思绪</a>
